#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import urllib3
import json

def es(cmd):
    try:
        header = { 'Content-Type': 'application/json' }
        data = {}
        if cmd[1] == "i":
            es_rtn('GET', cmd[2], data, header)
        else:
            print "incorrect commands"
    except IndexError:
        print "Usage : ./esbot [options] [Cluster URL]\n\n\
        i : ES Info\n\
        "

def es_rtn(method, cmd, data=None, header=None):
    http = urllib3.PoolManager()

    try:
        rtn = http.request(method,cmd,body=json.dumps(data),headers=header)
    except urllib3.exceptions.HTTPError as errh:
        print ("Http Error:",errh)

    print rtn.data

if __name__ == '__main__':
    es(sys.argv)
