#!/bin/sh

ES_VER="7.3.0"
ES_URL="https://artifacts.elastic.co/downloads/elasticsearch"
ES_RPM="elasticsearch-${ES_VER}-x86_64.rpm"

ES_ETC="/etc/elasticsearch"
ES_MYML="elasticsearch.yml"
ES_ADDYML="ymladd.yml"
ES_JVM="jvm.options"

ES_NODEIP=$(ifconfig | grep inet | grep -vE '127.0.0.1|inet6' | awk '{print $2}')
ES_NODENAME=$(hostname -s)

KB_URL="https://artifacts.elastic.co/downloads/kibana"
KB_RPM="kibana-${ES_VER}-x86_64.rpm"
KB_ETC="/etc/kibana"
KB_MYML="kibana.yml"

SEQ="1st"
ORG_SEQ="org_1st"

git pull

# ES Package Install
function install_es_packages
{
    wget 2> /dev/null
    if [ $? -ne 1 ]; then
        sudo yum -y install wget
    fi

    ls -alh /usr/local/src/elasticsearch* 2> /dev/null
    if [ $? -ne 0 ]; then
        sudo wget -q ${ES_URL}/${ES_RPM} -O /usr/local/src/${ES_RPM}
    fi

    rpm -ql elasticsearch > /dev/null
    if [ $? -ne 0 ]; then
        sudo rpm -ivh /usr/local/src/${ES_RPM}
    fi
}

# elasticsearch.yml Configure
function configure_es_yaml
{
    sudo cp -f ${ES_ETC}/${ES_MYML} ${ES_ETC}/${ES_MYML}.${ORG_SEQ}
    sudo cp -f ${ES_MYML}.${SEQ} ${ES_ETC}/${ES_MYML}
    sudo echo "### For ClusterName & Node Name" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    sudo echo "cluster.name: mytuto-es" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    sudo echo "node.name: master-$ES_NODENAME" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    
    sudo cat ${ES_ADDYML}.${SEQ} | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null

    sudo echo "### Discovery Settings" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    sudo echo "discovery.seed_hosts: [ \"$ES_NODEIP:9300\",  ]" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null
    sudo echo "cluster.initial_master_nodes: [ \"$ES_NODEIP:9300\",  ]" | sudo tee -a ${ES_ETC}/${ES_MYML} > /dev/null

    # jvm options Configure for Heap Memory
    sudo cp -f ${ES_ETC}/${ES_JVM} ${ES_ETC}/${ES_JVM}.${ORG_SEQ}
    sudo cp -f ${ES_JVM}.${SEQ} ${ES_ETC}/${ES_JVM}

}

# Start Elasticsearch
function start_es_process
{
    sudo systemctl daemon-reload
    sudo systemctl enable elasticsearch.service
    sudo systemctl restart elasticsearch
}

# Kibana Package Install
function install_kb_packages
{
    ls -alh /usr/local/src/kibana* 2> /dev/null
    if [ $? -ne 0 ]; then
        sudo wget -q ${KB_URL}/${KB_RPM} -O /usr/local/src/${KB_RPM}
    fi

    rpm -ql kibana > /dev/null
    if [ $? -ne 0 ]; then
        sudo rpm -ivh /usr/local/src/${KB_RPM}
    fi
}

# kibana.yml Configure
function configure_kb_yaml
{
    sudo cp -f ${KB_ETC}/${KB_MYML} ${KB_ETC}/${KB_MYML}.${ORG_SEQ}
    sudo cp -f ${KB_MYML} ${KB_ETC}/${KB_MYML}
}

# Start Kibana
function start_kb_process
{
    sudo systemctl daemon-reload
    sudo systemctl enable kibana.service
    sudo systemctl restart kibana
}

if [ -z $1 ]; then
        echo "##################### Menu ##############"
        echo " $ ./tuto1 [Command]"
        echo "#####################%%%%%%##############"
        echo "         1 : elasticsearch packages"
        echo "         2 : configure elasticsearch.yml & jvm.options"
        echo "         3 : start elasticsearch process"
        echo "         4 : install kibana packages"
        echo "         5 : configure kibana.yml"
        echo "         6 : start kibana process"
        echo "#########################################";
        exit 1;
fi

case "$1" in
        "1" ) install_es_packages;;
        "2" ) configure_es_yaml;;
        "3" ) start_es_process;;
        "4" ) install_kb_packages;;
        "5" ) configure_kb_yaml;;
        "6" ) start_kb_process;;
        *) echo "Incorrect Command" ;;
esac
