#!/bin/sh

ES=$1

if [ -z $ES ]; then
    echo "Usage : ./bulk localhost:9200"
else
    while(true); do
        curl -s -H 'Content-Type: application/x-ndjson' -XPOST "${ES}/bank/account/_bulk?pretty" --data-binary @accounts.json > /dev/null
	python monworker.py
	sleep 1

    done
fi

